/** This file is generated by {@link :js:js.test:generateJsExportOnFileTestFilesForTS} task. DO NOT MODIFY MANUALLY */

// CHECK_TYPESCRIPT_DECLARATIONS
// RUN_PLAIN_BOX_FUNCTION
// SKIP_MINIFICATION
// SKIP_NODE_JS
// INFER_MAIN_MODULE
// MODULE: JS_TESTS
// FILE: abstract-classes.kt

@file:JsExport

package foo


@Deprecated
fun foo() {}


@Deprecated
val bar: String = "Test"


var test: String
    get() = "Test"
    @Deprecated set() { console.log("Test") }


@Deprecated
class TestClass


class AnotherClass @Deprecated constructor(val value: String) {
    @JsName("fromNothing")
    @Deprecated constructor(): this("Test")

    @JsName("fromInt")
    constructor(value: Int): this(value.toString())

    @Deprecated
    fun foo() {}

    fun baz() {}

    @Deprecated
    val bar: String = "Test"

    var test: String
        get() = "Test"
        @Deprecated set() { console.log("Test") }
}


interface TestInterface {
    @Deprecated
    fun foo()
    fun bar()
    @Deprecated
    val bar: String
}


object TestObject {
    @Deprecated
    fun foo() {}
    fun bar() {}
    @Deprecated
    val bar: String = "Test"
}
